changes to _helpers.tpl in order to fix error
gremlin/helm pull request #15
Opened 2019-12-10 22:44 UTC by bn-openx

Got these issues when installing gremlin via helm:

`helm install gremlin/gremlin \ 
\--namespace gremlin \
\--name gremlin \
\--set gremlin.teamID=$GREMLIN_TEAM_ID \
\--set gremlin.clusterID=$GREMLIN_CLUSTER_ID
Error: parse error in "gremlin/templates/_helpers.tpl": template: gremlin/templates/_helpers.tpl:41: unexpected "=" in operand`

`helm install gremlin/gremlin \ 
\--namespace gremlin \
\--name gremlin \
\--set gremlin.teamID=$GREMLIN_TEAM_ID \
\--set gremlin.clusterID=$GREMLIN_CLUSTER_ID
Error: parse error in "gremlin/templates/_helpers.tpl": template: gremlin/templates/_helpers.tpl:43: unexpected "=" in operand`

`helm install ./ \                                                                            
\--namespace gremlin \
\--name gremlin \
\--set gremlin.teamID=$GREMLIN_TEAM_ID \
\--set gremlin.clusterID=$GREMLIN_CLUSTER_ID  
Error: release gremlin failed: DaemonSet.apps "gremlin" is invalid: [spec.template.spec.volumes[4].secret.secretName: Required value, spec.template.spec.containers[0].volumeMounts[4].name: Not found: "gremlin-cert"]`

The PR I am submitting are the changes I made to fix the helm chart and get everything to work. Please let me know if there's anything else you need from me.

2019-12-19 16:14 UTC, gremlin-thor commented
Thanks for the PR! I have a couple of questions so var as I'm working through this:

- What version of helm are you using? Can you post the output of `helm version`?
- Does `helm template` work for you?

2019-12-20 01:35 UTC, bn-openx commented
> Thanks for the PR! I have a couple of questions so var as I'm working through this:
> 
> * What version of helm are you using? Can you post the output of `helm version`?

`helm-2.11.0 version
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
`
> * Does `helm template` work for you?

`helm template ./` from my local gremlin repo does work correctly (can provide output but it's quite long).

2020-11-20 00:46 UTC, philgebhardt requested changes
Thanks for the pull request. It looks like this issue is related to illegal use of `=` in [helm 2.11.0 because it uses Golang 1.10 and does not support this operator](https://github.com/helm/helm/issues/4987#issuecomment-444285485).

The changes I've requested here are to avoid the use of assignments completely, just to remove some complexity here while we're at it. Thanks again!

2020-11-20 00:46 UTC, philgebhardt commented on gremlin/templates/_helpers.tpl
> +{{- $defaultName := "gremlin-team-cert" -}}
```suggestion
```

2020-11-20 00:46 UTC, philgebhardt commented on gremlin/templates/_helpers.tpl
> +{{- $defaultName := "gremlin-secret" -}}
```suggestion
{{- default .Values.gremlin.client.secretName .Values.gremlin.secret.name | default "gremlin-secret" -}}
```

2020-11-20 00:46 UTC, philgebhardt commented on gremlin/templates/_helpers.tpl
> +{{- $defaultName := "gremlin-team-cert" -}}
```suggestion
{{- default .Values.gremlin.client.secretName .Values.gremlin.secret.name | default "gremlin-team-cert" -}}
```

2020-11-20 00:46 UTC, philgebhardt commented on gremlin/templates/_helpers.tpl
>  {{- default .Values.gremlin.client.secretName .Values.gremlin.secret.name | default $defaultName -}}
```suggestion
```

2020-11-20 00:48 UTC, philgebhardt approved these changes

2020-11-20 00:48 UTC, merged